;this file for FamiTone2 library generated by text2data tool

Ritual_01c_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,245,204

@instruments:
	.byte $30 ;instrument $00
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $02
	.word @env2,@env8,@env0
	.byte $00
	.byte $70 ;instrument $03
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env5,@env9,@env0
	.byte $00
	.byte $30 ;instrument $08
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $09
	.word @env7,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $0a
	.word @env7,@env10,@env0
	.byte $00
	.byte $b0 ;instrument $0b
	.word @env7,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cb,$ce,$ca,$c4,$c2,$c1,$c0,$00,$06
@env2:
	.byte $ce,$ce,$cd,$cc,$cb,$ca,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00
	.byte $0e
@env3:
	.byte $c3,$c6,$c8,$ca,$cc,$cd,$03,$cb,$c9,$c8,$c7,$c6,$c5,$c5,$c4,$c3
	.byte $c2,$c0,$00,$11
@env4:
	.byte $ca,$cf,$ca,$c6,$c4,$c3,$c2,$c2,$c1,$04,$c0,$00,$0a
@env5:
	.byte $c8,$c8,$cb,$cb,$cf,$cf,$c0,$00,$06
@env6:
	.byte $cf,$ce,$cd,$cd,$cc,$cb,$ca,$ca,$c9,$c8,$c7,$c7,$c6,$c5,$c4,$c3
	.byte $c3,$c2,$c1,$c0,$00,$13
@env7:
	.byte $cf,$00,$00
@env8:
	.byte $b4,$c0,$b4,$c0,$cc,$c0,$00,$05
@env9:
	.byte $c0,$c0,$c5,$c5,$cc,$cc,$00,$05
@env10:
	.byte $c0,$c0,$cc,$cc,$00,$00


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $87,$84,$14,$85,$14,$85,$14,$85,$14,$85,$14,$85,$14,$85,$14,$85
@ref1:
	.byte $14,$85,$14,$85,$14,$85,$14,$85,$10,$85,$10,$85,$10,$85,$10,$85
@ref2:
	.byte $87,$14,$85,$14,$85,$14,$85,$14,$85,$14,$85,$14,$85,$14,$85
@ref3:
	.byte $14,$85,$14,$85,$14,$85,$14,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85
@ref4:
	.byte $86,$2c,$85,$2c,$85,$2d,$33,$37,$41,$44,$85,$44,$85,$44,$85,$41
	.byte $3a,$81
@ref5:
	.byte $40,$85,$40,$85,$40,$85,$3b,$37,$2c,$85,$2c,$85,$2c,$85,$2d,$28
	.byte $81
@ref6:
	.byte $2c,$85,$2c,$85,$2d,$33,$37,$41,$44,$85,$44,$85,$44,$85,$41,$3a
	.byte $81
@ref7:
	.byte $40,$85,$40,$85,$41,$45,$3b,$37,$2c,$85,$2c,$85,$2d,$29,$2c,$85
@ref8:
	.byte $92,$2c,$85,$2c,$85,$2d,$33,$37,$41,$44,$85,$44,$85,$44,$85,$41
	.byte $3a,$81
@ref9:
	.byte $40,$85,$40,$85,$41,$45,$3b,$37,$2c,$85,$2c,$85,$2d,$28,$89
	.byte $ff,$11
	.word @ref6
	.byte $ff,$0f
	.word @ref9
@ref12:
	.byte $90,$44,$85,$4a,$85,$45,$3b,$41,$45,$44,$85,$4e,$85,$52,$85,$4e
	.byte $85
@ref13:
	.byte $92,$36,$85,$3a,$85,$37,$37,$33,$2d,$2c,$85,$28,$85,$2c,$8d
@ref14:
	.byte $90,$45,$3b,$41,$45,$45,$3b,$41,$45,$4a,$85,$48,$85,$44,$85,$3a
	.byte $85
@ref15:
	.byte $92,$37,$2d,$37,$3b,$36,$85,$40,$85,$44,$85,$40,$85,$44,$8d
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref16:
	.byte $84,$0b,$14,$85,$14,$85,$14,$85,$14,$85,$14,$85,$14,$85,$14,$85
	.byte $14,$81
@ref17:
	.byte $0b,$14,$85,$14,$85,$14,$85,$14,$85,$10,$85,$10,$85,$10,$85,$86
	.byte $10,$81
	.byte $ff,$11
	.word @ref16
@ref19:
	.byte $0b,$14,$85,$14,$85,$14,$85,$14,$85,$1a,$85,$1a,$85,$1a,$85,$1a
	.byte $81
@ref20:
	.byte $83,$15,$86,$15,$84,$15,$86,$15,$84,$15,$86,$15,$84,$11,$86,$11
	.byte $84,$15,$86,$15,$84,$15,$86,$15,$84,$15,$86,$15,$84,$10,$81
@ref21:
	.byte $86,$11,$84,$15,$86,$15,$84,$15,$86,$15,$84,$15,$86,$15,$84,$11
	.byte $86,$11,$84,$15,$86,$15,$84,$15,$86,$15,$84,$15,$86,$15,$84,$10
	.byte $81
	.byte $ff,$11
	.word @ref20
@ref23:
	.byte $86,$11,$84,$1b,$1b,$1b,$1b,$1b,$1b,$1b,$1b,$15,$86,$15,$84,$15
	.byte $86,$15,$84,$15,$86,$15,$84,$10,$81
@ref24:
	.byte $83,$15,$8a,$15,$84,$15,$8a,$2d,$84,$15,$8a,$15,$84,$11,$8a,$11
	.byte $84,$15,$8a,$15,$84,$15,$8a,$15,$84,$15,$8a,$15,$84,$10,$81
@ref25:
	.byte $8a,$11,$84,$11,$8a,$11,$84,$11,$8a,$11,$84,$11,$8a,$11,$84,$11
	.byte $8a,$11,$84,$15,$8a,$15,$84,$15,$8a,$15,$84,$15,$8a,$15,$84,$10
	.byte $81
	.byte $ff,$11
	.word @ref24
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref24
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref24
	.byte $ff,$11
	.word @ref25
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref32:
	.byte $bf
@ref33:
	.byte $bf
@ref34:
	.byte $bf
@ref35:
	.byte $bf
@ref36:
	.byte $bf
@ref37:
	.byte $bf
@ref38:
	.byte $bf
@ref39:
	.byte $bf
@ref40:
	.byte $88,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
	.byte $2c,$81
@ref41:
	.byte $29,$29,$29,$29,$29,$29,$29,$23,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2c
	.byte $81
@ref42:
	.byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2c
	.byte $81
	.byte $ff,$11
	.word @ref41
	.byte $ff,$11
	.word @ref42
	.byte $ff,$11
	.word @ref41
	.byte $ff,$11
	.word @ref42
	.byte $ff,$11
	.word @ref41
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref48:
	.byte $80,$20,$8d,$8c,$0e,$8d,$80,$20,$8d,$8c,$0e,$8d
	.byte $ff,$08
	.word @ref48
	.byte $ff,$08
	.word @ref48
@ref51:
	.byte $80,$20,$8d,$8c,$0e,$8d,$80,$20,$8d,$8c,$0e,$85,$07,$0e,$81
@ref52:
	.byte $82,$20,$8d,$8c,$0e,$8d,$80,$20,$8d,$8c,$0f,$80,$08,$89
@ref53:
	.byte $20,$8d,$8c,$0e,$8d,$80,$20,$8d,$8c,$0f,$82,$09,$0b,$0e,$81
	.byte $ff,$08
	.word @ref48
@ref55:
	.byte $80,$20,$8d,$8c,$0e,$8d,$80,$20,$8d,$82,$0e,$0f,$80,$0f,$82,$0e
	.byte $8c,$0e,$81
@ref56:
	.byte $80,$20,$85,$8c,$0e,$85,$80,$20,$85,$8c,$0f,$80,$21,$20,$85,$8c
	.byte $0e,$85,$80,$20,$85,$8c,$0f,$80,$20,$81
@ref57:
	.byte $20,$85,$8c,$0e,$85,$80,$21,$21,$8c,$0f,$80,$21,$20,$85,$8c,$0e
	.byte $85,$80,$20,$85,$0e,$0e,$20,$20
@ref58:
	.byte $20,$85,$8c,$0e,$85,$80,$20,$85,$8c,$0f,$80,$21,$20,$85,$8c,$0e
	.byte $85,$80,$21,$8c,$0f,$0f,$80,$20,$81
@ref59:
	.byte $20,$85,$8c,$0e,$85,$80,$21,$21,$8c,$0f,$80,$21,$20,$85,$8c,$0f
	.byte $8e,$21,$8c,$0e,$80,$20,$82,$05,$80,$0e,$0e,$20,$20
@ref60:
	.byte $20,$85,$8c,$0e,$85,$80,$20,$85,$8c,$0f,$80,$21,$20,$85,$8c,$0e
	.byte $85,$80,$20,$85,$8c,$0f,$80,$20,$81
	.byte $ff,$12
	.word @ref57
	.byte $ff,$11
	.word @ref58
	.byte $ff,$13
	.word @ref59
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref64:
	.byte $33,$37,$37,$36,$85,$37,$37,$37,$33,$37,$37,$36,$85,$37,$37,$36
	.byte $81
	.byte $ff,$11
	.word @ref64
	.byte $ff,$11
	.word @ref64
	.byte $ff,$11
	.word @ref64
	.byte $ff,$11
	.word @ref64
	.byte $ff,$11
	.word @ref64
	.byte $ff,$11
	.word @ref64
@ref71:
	.byte $33,$37,$37,$36,$85,$37,$37,$37,$33,$37,$37,$37,$36,$33,$33,$32
	.byte $36,$81
@ref72:
	.byte $33,$36,$85,$37,$33,$36,$85,$33,$33,$36,$85,$37,$33,$36,$85,$32
	.byte $81
@ref73:
	.byte $33,$36,$89,$33,$32,$85,$33,$33,$36,$85,$37,$33,$36,$85,$32,$32
	.byte $ff,$11
	.word @ref72
@ref75:
	.byte $33,$36,$85,$37,$33,$32,$85,$33,$33,$36,$85,$33,$33,$36,$85,$36
	.byte $81
	.byte $ff,$11
	.word @ref72
	.byte $ff,$10
	.word @ref73
	.byte $ff,$11
	.word @ref72
	.byte $ff,$11
	.word @ref75
	.byte $fd
	.word @song0ch4loop
